<?php

/**
 * @file
 * Contains ckeditor_bs_boxy.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ckeditor_bs_boxy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_bs_boxy module.
    case 'help.page.ckeditor_bs_boxy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Ckeditor plugin for Bootstrap Boxy') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ckeditor_bs_boxy_theme($existing, $type, $theme, $path) {
  return [
    'form_element_label__bs_boxy_option' => [
      'base hook' => 'form_element_label',
      'template' => 'form-element-label-bs-boxy-option',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ckeditor_bs_boxy_preprocess_form_element(&$variables) {
  // If the flag is available we use a special function to render the label.
  if (isset($variables['element']['#attributes']['data-bs-boxy-option'])) {
    $variables['attributes']['class'] = $variables['attributes']['class'] ?? [];
    $variables['attributes']['class'] += ['d-block', 'm-0', 'bs-boxy-option'];
    $variables['label']['#theme'] = 'form_element_label__bs_boxy_option';
    $variables['label']['#bs_option_value'] = $variables['element']['#return_value'];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ckeditor_bs_boxy_preprocess_form_element_label(&$variables) {
  if (!empty($variables['element']['#bs_option_value'])) {
    $variables['bs_option_values'] = explode('_', $variables['element']['#bs_option_value']);
  }
}
